// Appointment Status
export const APPOINTMENT_STATUS = {
  SCHEDULED: 'scheduled',
  CONFIRMED: 'confirmed',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
  RESCHEDULED: 'rescheduled',
  PENDING: 'pending',
  CONFIRMED_BY_CUSTOMER: 'confirmed_by_customer',
  CONFIRMED_BY_STAFF: 'confirmed_by_staff',
  WAITING: 'waiting',
  READY: 'ready',
}

// Appointment status display names
export const APPOINTMENT_STATUS_DISPLAY_NAMES = {
  [APPOINTMENT_STATUS.SCHEDULED]: 'Scheduled',
  [APPOINTMENT_STATUS.CONFIRMED]: 'Confirmed',
  [APPOINTMENT_STATUS.IN_PROGRESS]: 'In Progress',
  [APPOINTMENT_STATUS.COMPLETED]: 'Completed',
  [APPOINTMENT_STATUS.CANCELLED]: 'Cancelled',
  [APPOINTMENT_STATUS.NO_SHOW]: 'No Show',
  [APPOINTMENT_STATUS.RESCHEDULED]: 'Rescheduled',
  [APPOINTMENT_STATUS.PENDING]: 'Pending',
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: 'Confirmed by Customer',
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: 'Confirmed by Staff',
  [APPOINTMENT_STATUS.WAITING]: 'Waiting',
  [APPOINTMENT_STATUS.READY]: 'Ready',
}

// Appointment status descriptions
export const APPOINTMENT_STATUS_DESCRIPTIONS = {
  [APPOINTMENT_STATUS.SCHEDULED]: 'Appointment has been scheduled',
  [APPOINTMENT_STATUS.CONFIRMED]: 'Appointment has been confirmed',
  [APPOINTMENT_STATUS.IN_PROGRESS]: 'Appointment is currently in progress',
  [APPOINTMENT_STATUS.COMPLETED]: 'Appointment has been completed',
  [APPOINTMENT_STATUS.CANCELLED]: 'Appointment has been cancelled',
  [APPOINTMENT_STATUS.NO_SHOW]: 'Customer did not show up for appointment',
  [APPOINTMENT_STATUS.RESCHEDULED]: 'Appointment has been rescheduled',
  [APPOINTMENT_STATUS.PENDING]: 'Appointment is pending confirmation',
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: 'Confirmed by customer',
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: 'Confirmed by staff member',
  [APPOINTMENT_STATUS.WAITING]: 'Customer is waiting for service',
  [APPOINTMENT_STATUS.READY]: 'Service is ready to begin',
}

// Appointment status colors
export const APPOINTMENT_STATUS_COLORS = {
  [APPOINTMENT_STATUS.SCHEDULED]: 'blue',
  [APPOINTMENT_STATUS.CONFIRMED]: 'green',
  [APPOINTMENT_STATUS.IN_PROGRESS]: 'orange',
  [APPOINTMENT_STATUS.COMPLETED]: 'green',
  [APPOINTMENT_STATUS.CANCELLED]: 'red',
  [APPOINTMENT_STATUS.NO_SHOW]: 'red',
  [APPOINTMENT_STATUS.RESCHEDULED]: 'yellow',
  [APPOINTMENT_STATUS.PENDING]: 'gray',
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: 'green',
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: 'green',
  [APPOINTMENT_STATUS.WAITING]: 'purple',
  [APPOINTMENT_STATUS.READY]: 'teal',
}

// Appointment status icons
export const APPOINTMENT_STATUS_ICONS = {
  [APPOINTMENT_STATUS.SCHEDULED]: 'calendar',
  [APPOINTMENT_STATUS.CONFIRMED]: 'check-circle',
  [APPOINTMENT_STATUS.IN_PROGRESS]: 'clock',
  [APPOINTMENT_STATUS.COMPLETED]: 'check',
  [APPOINTMENT_STATUS.CANCELLED]: 'times-circle',
  [APPOINTMENT_STATUS.NO_SHOW]: 'exclamation-triangle',
  [APPOINTMENT_STATUS.RESCHEDULED]: 'calendar-alt',
  [APPOINTMENT_STATUS.PENDING]: 'hourglass-half',
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: 'user-check',
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: 'user-tie',
  [APPOINTMENT_STATUS.WAITING]: 'clock',
  [APPOINTMENT_STATUS.READY]: 'play',
}

// Appointment status categories
export const APPOINTMENT_STATUS_CATEGORIES = {
  UPCOMING: 'upcoming',
  ACTIVE: 'active',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  PENDING: 'pending',
}

// Appointment status to category mapping
export const APPOINTMENT_STATUS_CATEGORY_MAPPING = {
  [APPOINTMENT_STATUS.SCHEDULED]: APPOINTMENT_STATUS_CATEGORIES.UPCOMING,
  [APPOINTMENT_STATUS.CONFIRMED]: APPOINTMENT_STATUS_CATEGORIES.UPCOMING,
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: APPOINTMENT_STATUS_CATEGORIES.UPCOMING,
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: APPOINTMENT_STATUS_CATEGORIES.UPCOMING,
  [APPOINTMENT_STATUS.IN_PROGRESS]: APPOINTMENT_STATUS_CATEGORIES.ACTIVE,
  [APPOINTMENT_STATUS.WAITING]: APPOINTMENT_STATUS_CATEGORIES.ACTIVE,
  [APPOINTMENT_STATUS.READY]: APPOINTMENT_STATUS_CATEGORIES.ACTIVE,
  [APPOINTMENT_STATUS.COMPLETED]: APPOINTMENT_STATUS_CATEGORIES.COMPLETED,
  [APPOINTMENT_STATUS.CANCELLED]: APPOINTMENT_STATUS_CATEGORIES.CANCELLED,
  [APPOINTMENT_STATUS.NO_SHOW]: APPOINTMENT_STATUS_CATEGORIES.CANCELLED,
  [APPOINTMENT_STATUS.RESCHEDULED]: APPOINTMENT_STATUS_CATEGORIES.UPCOMING,
  [APPOINTMENT_STATUS.PENDING]: APPOINTMENT_STATUS_CATEGORIES.PENDING,
}

// Appointment status priority (higher number = higher priority)
export const APPOINTMENT_STATUS_PRIORITY = {
  [APPOINTMENT_STATUS.IN_PROGRESS]: 5,
  [APPOINTMENT_STATUS.READY]: 4,
  [APPOINTMENT_STATUS.WAITING]: 4,
  [APPOINTMENT_STATUS.CONFIRMED]: 3,
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: 3,
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: 3,
  [APPOINTMENT_STATUS.SCHEDULED]: 2,
  [APPOINTMENT_STATUS.PENDING]: 2,
  [APPOINTMENT_STATUS.RESCHEDULED]: 2,
  [APPOINTMENT_STATUS.COMPLETED]: 1,
  [APPOINTMENT_STATUS.CANCELLED]: 0,
  [APPOINTMENT_STATUS.NO_SHOW]: 0,
}

// Appointment status transitions (what statuses can be changed to)
export const APPOINTMENT_STATUS_TRANSITIONS = {
  [APPOINTMENT_STATUS.SCHEDULED]: [APPOINTMENT_STATUS.CONFIRMED, APPOINTMENT_STATUS.CANCELLED, APPOINTMENT_STATUS.RESCHEDULED],
  [APPOINTMENT_STATUS.CONFIRMED]: [APPOINTMENT_STATUS.IN_PROGRESS, APPOINTMENT_STATUS.CANCELLED, APPOINTMENT_STATUS.RESCHEDULED, APPOINTMENT_STATUS.NO_SHOW],
  [APPOINTMENT_STATUS.IN_PROGRESS]: [APPOINTMENT_STATUS.COMPLETED, APPOINTMENT_STATUS.CANCELLED],
  [APPOINTMENT_STATUS.COMPLETED]: [], // Terminal state
  [APPOINTMENT_STATUS.CANCELLED]: [APPOINTMENT_STATUS.SCHEDULED], // Can reschedule
  [APPOINTMENT_STATUS.NO_SHOW]: [APPOINTMENT_STATUS.SCHEDULED], // Can reschedule
  [APPOINTMENT_STATUS.RESCHEDULED]: [APPOINTMENT_STATUS.SCHEDULED, APPOINTMENT_STATUS.CONFIRMED],
  [APPOINTMENT_STATUS.PENDING]: [APPOINTMENT_STATUS.CONFIRMED, APPOINTMENT_STATUS.CANCELLED],
  [APPOINTMENT_STATUS.CONFIRMED_BY_CUSTOMER]: [APPOINTMENT_STATUS.IN_PROGRESS, APPOINTMENT_STATUS.CANCELLED, APPOINTMENT_STATUS.NO_SHOW],
  [APPOINTMENT_STATUS.CONFIRMED_BY_STAFF]: [APPOINTMENT_STATUS.IN_PROGRESS, APPOINTMENT_STATUS.CANCELLED, APPOINTMENT_STATUS.NO_SHOW],
  [APPOINTMENT_STATUS.WAITING]: [APPOINTMENT_STATUS.IN_PROGRESS, APPOINTMENT_STATUS.READY, APPOINTMENT_STATUS.CANCELLED],
  [APPOINTMENT_STATUS.READY]: [APPOINTMENT_STATUS.IN_PROGRESS, APPOINTMENT_STATUS.CANCELLED],
}

// Available appointment statuses for selection
export const AVAILABLE_APPOINTMENT_STATUSES = Object.values(APPOINTMENT_STATUS).map(status => ({
  value: status,
  label: APPOINTMENT_STATUS_DISPLAY_NAMES[status],
  description: APPOINTMENT_STATUS_DESCRIPTIONS[status],
  color: APPOINTMENT_STATUS_COLORS[status],
  icon: APPOINTMENT_STATUS_ICONS[status],
  category: APPOINTMENT_STATUS_CATEGORY_MAPPING[status],
  priority: APPOINTMENT_STATUS_PRIORITY[status],
  transitions: APPOINTMENT_STATUS_TRANSITIONS[status],
}))

export default {
  APPOINTMENT_STATUS,
  APPOINTMENT_STATUS_DISPLAY_NAMES,
  APPOINTMENT_STATUS_DESCRIPTIONS,
  APPOINTMENT_STATUS_COLORS,
  APPOINTMENT_STATUS_ICONS,
  APPOINTMENT_STATUS_CATEGORIES,
  APPOINTMENT_STATUS_CATEGORY_MAPPING,
  APPOINTMENT_STATUS_PRIORITY,
  APPOINTMENT_STATUS_TRANSITIONS,
  AVAILABLE_APPOINTMENT_STATUSES,
}
