// Booking Sources
export const BOOKING_SOURCES = {
  WEBSITE: 'website',
  MOBILE_APP: 'mobile_app',
  PHONE: 'phone',
  WALK_IN: 'walk_in',
  SOCIAL_MEDIA: 'social_media',
  EMAIL: 'email',
  REFERRAL: 'referral',
  GOOGLE: 'google',
  FACEBOOK: 'facebook',
  INSTAGRAM: 'instagram',
  YELP: 'yelp',
  BOOKING_COM: 'booking_com',
  STAFF_BOOKING: 'staff_booking',
  MANAGER_BOOKING: 'manager_booking',
  ADMIN_BOOKING: 'admin_booking',
  OTHER: 'other',
}

// Booking source display names
export const BOOKING_SOURCE_DISPLAY_NAMES = {
  [BOOKING_SOURCES.WEBSITE]: 'Website',
  [BOOKING_SOURCES.MOBILE_APP]: 'Mobile App',
  [BOOKING_SOURCES.PHONE]: 'Phone Call',
  [BOOKING_SOURCES.WALK_IN]: 'Walk-in',
  [BOOKING_SOURCES.SOCIAL_MEDIA]: 'Social Media',
  [BOOKING_SOURCES.EMAIL]: 'Email',
  [BOOKING_SOURCES.REFERRAL]: 'Referral',
  [BOOKING_SOURCES.GOOGLE]: 'Google',
  [BOOKING_SOURCES.FACEBOOK]: 'Facebook',
  [BOOKING_SOURCES.INSTAGRAM]: 'Instagram',
  [BOOKING_SOURCES.YELP]: 'Yelp',
  [BOOKING_SOURCES.BOOKING_COM]: 'Booking.com',
  [BOOKING_SOURCES.STAFF_BOOKING]: 'Staff Booking',
  [BOOKING_SOURCES.MANAGER_BOOKING]: 'Manager Booking',
  [BOOKING_SOURCES.ADMIN_BOOKING]: 'Admin Booking',
  [BOOKING_SOURCES.OTHER]: 'Other',
}

// Booking source descriptions
export const BOOKING_SOURCE_DESCRIPTIONS = {
  [BOOKING_SOURCES.WEBSITE]: 'Booked through the business website',
  [BOOKING_SOURCES.MOBILE_APP]: 'Booked through the mobile application',
  [BOOKING_SOURCES.PHONE]: 'Booked via phone call',
  [BOOKING_SOURCES.WALK_IN]: 'Customer walked in without prior booking',
  [BOOKING_SOURCES.SOCIAL_MEDIA]: 'Booked through social media platforms',
  [BOOKING_SOURCES.EMAIL]: 'Booked via email communication',
  [BOOKING_SOURCES.REFERRAL]: 'Booked through customer referral',
  [BOOKING_SOURCES.GOOGLE]: 'Booked through Google search or ads',
  [BOOKING_SOURCES.FACEBOOK]: 'Booked through Facebook',
  [BOOKING_SOURCES.INSTAGRAM]: 'Booked through Instagram',
  [BOOKING_SOURCES.YELP]: 'Booked through Yelp',
  [BOOKING_SOURCES.BOOKING_COM]: 'Booked through Booking.com',
  [BOOKING_SOURCES.STAFF_BOOKING]: 'Booked by staff member',
  [BOOKING_SOURCES.MANAGER_BOOKING]: 'Booked by manager',
  [BOOKING_SOURCES.ADMIN_BOOKING]: 'Booked by administrator',
  [BOOKING_SOURCES.OTHER]: 'Booked through other means',
}

// Booking source colors
export const BOOKING_SOURCE_COLORS = {
  [BOOKING_SOURCES.WEBSITE]: 'blue',
  [BOOKING_SOURCES.MOBILE_APP]: 'purple',
  [BOOKING_SOURCES.PHONE]: 'green',
  [BOOKING_SOURCES.WALK_IN]: 'orange',
  [BOOKING_SOURCES.SOCIAL_MEDIA]: 'pink',
  [BOOKING_SOURCES.EMAIL]: 'teal',
  [BOOKING_SOURCES.REFERRAL]: 'yellow',
  [BOOKING_SOURCES.GOOGLE]: 'red',
  [BOOKING_SOURCES.FACEBOOK]: 'blue',
  [BOOKING_SOURCES.INSTAGRAM]: 'pink',
  [BOOKING_SOURCES.YELP]: 'red',
  [BOOKING_SOURCES.BOOKING_COM]: 'blue',
  [BOOKING_SOURCES.STAFF_BOOKING]: 'green',
  [BOOKING_SOURCES.MANAGER_BOOKING]: 'purple',
  [BOOKING_SOURCES.ADMIN_BOOKING]: 'red',
  [BOOKING_SOURCES.OTHER]: 'gray',
}

// Booking source icons
export const BOOKING_SOURCE_ICONS = {
  [BOOKING_SOURCES.WEBSITE]: 'globe',
  [BOOKING_SOURCES.MOBILE_APP]: 'mobile-alt',
  [BOOKING_SOURCES.PHONE]: 'phone',
  [BOOKING_SOURCES.WALK_IN]: 'walking',
  [BOOKING_SOURCES.SOCIAL_MEDIA]: 'share-alt',
  [BOOKING_SOURCES.EMAIL]: 'envelope',
  [BOOKING_SOURCES.REFERRAL]: 'user-friends',
  [BOOKING_SOURCES.GOOGLE]: 'google',
  [BOOKING_SOURCES.FACEBOOK]: 'facebook',
  [BOOKING_SOURCES.INSTAGRAM]: 'instagram',
  [BOOKING_SOURCES.YELP]: 'yelp',
  [BOOKING_SOURCES.BOOKING_COM]: 'calendar-check',
  [BOOKING_SOURCES.STAFF_BOOKING]: 'user-tie',
  [BOOKING_SOURCES.MANAGER_BOOKING]: 'user-cog',
  [BOOKING_SOURCES.ADMIN_BOOKING]: 'user-shield',
  [BOOKING_SOURCES.OTHER]: 'question-circle',
}

// Booking source categories
export const BOOKING_SOURCE_CATEGORIES = {
  DIGITAL: 'digital',
  PHONE: 'phone',
  IN_PERSON: 'in_person',
  SOCIAL: 'social',
  REFERRAL: 'referral',
  STAFF: 'staff',
  OTHER: 'other',
}

// Booking source to category mapping
export const BOOKING_SOURCE_CATEGORY_MAPPING = {
  [BOOKING_SOURCES.WEBSITE]: BOOKING_SOURCE_CATEGORIES.DIGITAL,
  [BOOKING_SOURCES.MOBILE_APP]: BOOKING_SOURCE_CATEGORIES.DIGITAL,
  [BOOKING_SOURCES.EMAIL]: BOOKING_SOURCE_CATEGORIES.DIGITAL,
  [BOOKING_SOURCES.GOOGLE]: BOOKING_SOURCE_CATEGORIES.DIGITAL,
  [BOOKING_SOURCES.BOOKING_COM]: BOOKING_SOURCE_CATEGORIES.DIGITAL,
  [BOOKING_SOURCES.PHONE]: BOOKING_SOURCE_CATEGORIES.PHONE,
  [BOOKING_SOURCES.WALK_IN]: BOOKING_SOURCE_CATEGORIES.IN_PERSON,
  [BOOKING_SOURCES.SOCIAL_MEDIA]: BOOKING_SOURCE_CATEGORIES.SOCIAL,
  [BOOKING_SOURCES.FACEBOOK]: BOOKING_SOURCE_CATEGORIES.SOCIAL,
  [BOOKING_SOURCES.INSTAGRAM]: BOOKING_SOURCE_CATEGORIES.SOCIAL,
  [BOOKING_SOURCES.YELP]: BOOKING_SOURCE_CATEGORIES.SOCIAL,
  [BOOKING_SOURCES.REFERRAL]: BOOKING_SOURCE_CATEGORIES.REFERRAL,
  [BOOKING_SOURCES.STAFF_BOOKING]: BOOKING_SOURCE_CATEGORIES.STAFF,
  [BOOKING_SOURCES.MANAGER_BOOKING]: BOOKING_SOURCE_CATEGORIES.STAFF,
  [BOOKING_SOURCES.ADMIN_BOOKING]: BOOKING_SOURCE_CATEGORIES.STAFF,
  [BOOKING_SOURCES.OTHER]: BOOKING_SOURCE_CATEGORIES.OTHER,
}

// Booking source priority (higher number = higher priority for analytics)
export const BOOKING_SOURCE_PRIORITY = {
  [BOOKING_SOURCES.WEBSITE]: 5,
  [BOOKING_SOURCES.MOBILE_APP]: 5,
  [BOOKING_SOURCES.GOOGLE]: 4,
  [BOOKING_SOURCES.FACEBOOK]: 4,
  [BOOKING_SOURCES.INSTAGRAM]: 4,
  [BOOKING_SOURCES.REFERRAL]: 4,
  [BOOKING_SOURCES.EMAIL]: 3,
  [BOOKING_SOURCES.PHONE]: 3,
  [BOOKING_SOURCES.YELP]: 3,
  [BOOKING_SOURCES.BOOKING_COM]: 3,
  [BOOKING_SOURCES.SOCIAL_MEDIA]: 2,
  [BOOKING_SOURCES.WALK_IN]: 2,
  [BOOKING_SOURCES.STAFF_BOOKING]: 1,
  [BOOKING_SOURCES.MANAGER_BOOKING]: 1,
  [BOOKING_SOURCES.ADMIN_BOOKING]: 1,
  [BOOKING_SOURCES.OTHER]: 1,
}

// Available booking sources for selection
export const AVAILABLE_BOOKING_SOURCES = Object.values(BOOKING_SOURCES).map(source => ({
  value: source,
  label: BOOKING_SOURCE_DISPLAY_NAMES[source],
  description: BOOKING_SOURCE_DESCRIPTIONS[source],
  color: BOOKING_SOURCE_COLORS[source],
  icon: BOOKING_SOURCE_ICONS[source],
  category: BOOKING_SOURCE_CATEGORY_MAPPING[source],
  priority: BOOKING_SOURCE_PRIORITY[source],
}))

export default {
  BOOKING_SOURCES,
  BOOKING_SOURCE_DISPLAY_NAMES,
  BOOKING_SOURCE_DESCRIPTIONS,
  BOOKING_SOURCE_COLORS,
  BOOKING_SOURCE_ICONS,
  BOOKING_SOURCE_CATEGORIES,
  BOOKING_SOURCE_CATEGORY_MAPPING,
  BOOKING_SOURCE_PRIORITY,
  AVAILABLE_BOOKING_SOURCES,
}
