// Payment Methods
export const PAYMENT_METHODS = {
  CASH: 'cash',
  CREDIT_CARD: 'credit_card',
  DEBIT_CARD: 'debit_card',
  BANK_TRANSFER: 'bank_transfer',
  PAYPAL: 'paypal',
  STRIPE: 'stripe',
  SQUARE: 'square',
  VENMO: 'venmo',
  APPLE_PAY: 'apple_pay',
  GOOGLE_PAY: 'google_pay',
  SAMSUNG_PAY: 'samsung_pay',
  CHECK: 'check',
  GIFT_CARD: 'gift_card',
  LOYALTY_POINTS: 'loyalty_points',
  CREDIT: 'credit',
  FREE: 'free',
  OTHER: 'other',
}

// Payment method display names
export const PAYMENT_METHOD_DISPLAY_NAMES = {
  [PAYMENT_METHODS.CASH]: 'Cash',
  [PAYMENT_METHODS.CREDIT_CARD]: 'Credit Card',
  [PAYMENT_METHODS.DEBIT_CARD]: 'Debit Card',
  [PAYMENT_METHODS.BANK_TRANSFER]: 'Bank Transfer',
  [PAYMENT_METHODS.PAYPAL]: 'PayPal',
  [PAYMENT_METHODS.STRIPE]: 'Stripe',
  [PAYMENT_METHODS.SQUARE]: 'Square',
  [PAYMENT_METHODS.VENMO]: 'Venmo',
  [PAYMENT_METHODS.APPLE_PAY]: 'Apple Pay',
  [PAYMENT_METHODS.GOOGLE_PAY]: 'Google Pay',
  [PAYMENT_METHODS.SAMSUNG_PAY]: 'Samsung Pay',
  [PAYMENT_METHODS.CHECK]: 'Check',
  [PAYMENT_METHODS.GIFT_CARD]: 'Gift Card',
  [PAYMENT_METHODS.LOYALTY_POINTS]: 'Loyalty Points',
  [PAYMENT_METHODS.CREDIT]: 'Credit',
  [PAYMENT_METHODS.FREE]: 'Free',
  [PAYMENT_METHODS.OTHER]: 'Other',
}

// Payment method descriptions
export const PAYMENT_METHOD_DESCRIPTIONS = {
  [PAYMENT_METHODS.CASH]: 'Payment made with cash',
  [PAYMENT_METHODS.CREDIT_CARD]: 'Payment made with credit card',
  [PAYMENT_METHODS.DEBIT_CARD]: 'Payment made with debit card',
  [PAYMENT_METHODS.BANK_TRANSFER]: 'Payment made via bank transfer',
  [PAYMENT_METHODS.PAYPAL]: 'Payment made through PayPal',
  [PAYMENT_METHODS.STRIPE]: 'Payment processed through Stripe',
  [PAYMENT_METHODS.SQUARE]: 'Payment processed through Square',
  [PAYMENT_METHODS.VENMO]: 'Payment made through Venmo',
  [PAYMENT_METHODS.APPLE_PAY]: 'Payment made through Apple Pay',
  [PAYMENT_METHODS.GOOGLE_PAY]: 'Payment made through Google Pay',
  [PAYMENT_METHODS.SAMSUNG_PAY]: 'Payment made through Samsung Pay',
  [PAYMENT_METHODS.CHECK]: 'Payment made with check',
  [PAYMENT_METHODS.GIFT_CARD]: 'Payment made with gift card',
  [PAYMENT_METHODS.LOYALTY_POINTS]: 'Payment made with loyalty points',
  [PAYMENT_METHODS.CREDIT]: 'Payment made on credit',
  [PAYMENT_METHODS.FREE]: 'Free service or complimentary',
  [PAYMENT_METHODS.OTHER]: 'Other payment method',
}

// Payment method colors
export const PAYMENT_METHOD_COLORS = {
  [PAYMENT_METHODS.CASH]: 'green',
  [PAYMENT_METHODS.CREDIT_CARD]: 'blue',
  [PAYMENT_METHODS.DEBIT_CARD]: 'blue',
  [PAYMENT_METHODS.BANK_TRANSFER]: 'purple',
  [PAYMENT_METHODS.PAYPAL]: 'blue',
  [PAYMENT_METHODS.STRIPE]: 'purple',
  [PAYMENT_METHODS.SQUARE]: 'green',
  [PAYMENT_METHODS.VENMO]: 'blue',
  [PAYMENT_METHODS.APPLE_PAY]: 'gray',
  [PAYMENT_METHODS.GOOGLE_PAY]: 'blue',
  [PAYMENT_METHODS.SAMSUNG_PAY]: 'blue',
  [PAYMENT_METHODS.CHECK]: 'yellow',
  [PAYMENT_METHODS.GIFT_CARD]: 'pink',
  [PAYMENT_METHODS.LOYALTY_POINTS]: 'orange',
  [PAYMENT_METHODS.CREDIT]: 'red',
  [PAYMENT_METHODS.FREE]: 'green',
  [PAYMENT_METHODS.OTHER]: 'gray',
}

// Payment method icons
export const PAYMENT_METHOD_ICONS = {
  [PAYMENT_METHODS.CASH]: 'money-bill',
  [PAYMENT_METHODS.CREDIT_CARD]: 'credit-card',
  [PAYMENT_METHODS.DEBIT_CARD]: 'credit-card',
  [PAYMENT_METHODS.BANK_TRANSFER]: 'university',
  [PAYMENT_METHODS.PAYPAL]: 'paypal',
  [PAYMENT_METHODS.STRIPE]: 'stripe',
  [PAYMENT_METHODS.SQUARE]: 'square',
  [PAYMENT_METHODS.VENMO]: 'venmo',
  [PAYMENT_METHODS.APPLE_PAY]: 'apple',
  [PAYMENT_METHODS.GOOGLE_PAY]: 'google',
  [PAYMENT_METHODS.SAMSUNG_PAY]: 'samsung',
  [PAYMENT_METHODS.CHECK]: 'check',
  [PAYMENT_METHODS.GIFT_CARD]: 'gift',
  [PAYMENT_METHODS.LOYALTY_POINTS]: 'star',
  [PAYMENT_METHODS.CREDIT]: 'hand-holding-usd',
  [PAYMENT_METHODS.FREE]: 'gift',
  [PAYMENT_METHODS.OTHER]: 'question-circle',
}

// Payment method categories
export const PAYMENT_METHOD_CATEGORIES = {
  CASH: 'cash',
  CARD: 'card',
  DIGITAL: 'digital',
  BANK: 'bank',
  MOBILE: 'mobile',
  GIFT: 'gift',
  CREDIT: 'credit',
  OTHER: 'other',
}

// Payment method to category mapping
export const PAYMENT_METHOD_CATEGORY_MAPPING = {
  [PAYMENT_METHODS.CASH]: PAYMENT_METHOD_CATEGORIES.CASH,
  [PAYMENT_METHODS.CREDIT_CARD]: PAYMENT_METHOD_CATEGORIES.CARD,
  [PAYMENT_METHODS.DEBIT_CARD]: PAYMENT_METHOD_CATEGORIES.CARD,
  [PAYMENT_METHODS.BANK_TRANSFER]: PAYMENT_METHOD_CATEGORIES.BANK,
  [PAYMENT_METHODS.PAYPAL]: PAYMENT_METHOD_CATEGORIES.DIGITAL,
  [PAYMENT_METHODS.STRIPE]: PAYMENT_METHOD_CATEGORIES.DIGITAL,
  [PAYMENT_METHODS.SQUARE]: PAYMENT_METHOD_CATEGORIES.DIGITAL,
  [PAYMENT_METHODS.VENMO]: PAYMENT_METHOD_CATEGORIES.DIGITAL,
  [PAYMENT_METHODS.APPLE_PAY]: PAYMENT_METHOD_CATEGORIES.MOBILE,
  [PAYMENT_METHODS.GOOGLE_PAY]: PAYMENT_METHOD_CATEGORIES.MOBILE,
  [PAYMENT_METHODS.SAMSUNG_PAY]: PAYMENT_METHOD_CATEGORIES.MOBILE,
  [PAYMENT_METHODS.CHECK]: PAYMENT_METHOD_CATEGORIES.BANK,
  [PAYMENT_METHODS.GIFT_CARD]: PAYMENT_METHOD_CATEGORIES.GIFT,
  [PAYMENT_METHODS.LOYALTY_POINTS]: PAYMENT_METHOD_CATEGORIES.GIFT,
  [PAYMENT_METHODS.CREDIT]: PAYMENT_METHOD_CATEGORIES.CREDIT,
  [PAYMENT_METHODS.FREE]: PAYMENT_METHOD_CATEGORIES.GIFT,
  [PAYMENT_METHODS.OTHER]: PAYMENT_METHOD_CATEGORIES.OTHER,
}

// Payment method processing fees (percentage)
export const PAYMENT_METHOD_FEES = {
  [PAYMENT_METHODS.CASH]: 0,
  [PAYMENT_METHODS.CREDIT_CARD]: 2.9,
  [PAYMENT_METHODS.DEBIT_CARD]: 1.5,
  [PAYMENT_METHODS.BANK_TRANSFER]: 0.5,
  [PAYMENT_METHODS.PAYPAL]: 2.9,
  [PAYMENT_METHODS.STRIPE]: 2.9,
  [PAYMENT_METHODS.SQUARE]: 2.9,
  [PAYMENT_METHODS.VENMO]: 1.9,
  [PAYMENT_METHODS.APPLE_PAY]: 2.9,
  [PAYMENT_METHODS.GOOGLE_PAY]: 2.9,
  [PAYMENT_METHODS.SAMSUNG_PAY]: 2.9,
  [PAYMENT_METHODS.CHECK]: 0,
  [PAYMENT_METHODS.GIFT_CARD]: 0,
  [PAYMENT_METHODS.LOYALTY_POINTS]: 0,
  [PAYMENT_METHODS.CREDIT]: 0,
  [PAYMENT_METHODS.FREE]: 0,
  [PAYMENT_METHODS.OTHER]: 0,
}

// Payment method availability (online vs offline)
export const PAYMENT_METHOD_AVAILABILITY = {
  [PAYMENT_METHODS.CASH]: 'offline',
  [PAYMENT_METHODS.CREDIT_CARD]: 'both',
  [PAYMENT_METHODS.DEBIT_CARD]: 'both',
  [PAYMENT_METHODS.BANK_TRANSFER]: 'online',
  [PAYMENT_METHODS.PAYPAL]: 'online',
  [PAYMENT_METHODS.STRIPE]: 'online',
  [PAYMENT_METHODS.SQUARE]: 'both',
  [PAYMENT_METHODS.VENMO]: 'online',
  [PAYMENT_METHODS.APPLE_PAY]: 'both',
  [PAYMENT_METHODS.GOOGLE_PAY]: 'both',
  [PAYMENT_METHODS.SAMSUNG_PAY]: 'both',
  [PAYMENT_METHODS.CHECK]: 'offline',
  [PAYMENT_METHODS.GIFT_CARD]: 'both',
  [PAYMENT_METHODS.LOYALTY_POINTS]: 'both',
  [PAYMENT_METHODS.CREDIT]: 'offline',
  [PAYMENT_METHODS.FREE]: 'both',
  [PAYMENT_METHODS.OTHER]: 'both',
}

// Available payment methods for selection
export const AVAILABLE_PAYMENT_METHODS = Object.values(PAYMENT_METHODS).map(method => ({
  value: method,
  label: PAYMENT_METHOD_DISPLAY_NAMES[method],
  description: PAYMENT_METHOD_DESCRIPTIONS[method],
  color: PAYMENT_METHOD_COLORS[method],
  icon: PAYMENT_METHOD_ICONS[method],
  category: PAYMENT_METHOD_CATEGORY_MAPPING[method],
  fee: PAYMENT_METHOD_FEES[method],
  availability: PAYMENT_METHOD_AVAILABILITY[method],
}))

export default {
  PAYMENT_METHODS,
  PAYMENT_METHOD_DISPLAY_NAMES,
  PAYMENT_METHOD_DESCRIPTIONS,
  PAYMENT_METHOD_COLORS,
  PAYMENT_METHOD_ICONS,
  PAYMENT_METHOD_CATEGORIES,
  PAYMENT_METHOD_CATEGORY_MAPPING,
  PAYMENT_METHOD_FEES,
  PAYMENT_METHOD_AVAILABILITY,
  AVAILABLE_PAYMENT_METHODS,
}
