// Customer Status
export const CUSTOMER_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  SUSPENDED: 'suspended',
  BLOCKED: 'blocked',
  PENDING: 'pending',
  VERIFIED: 'verified',
  UNVERIFIED: 'unverified',
  VIP: 'vip',
  PREMIUM: 'premium',
  REGULAR: 'regular',
  NEW: 'new',
}

// Customer status display names
export const CUSTOMER_STATUS_DISPLAY_NAMES = {
  [CUSTOMER_STATUS.ACTIVE]: 'Active',
  [CUSTOMER_STATUS.INACTIVE]: 'Inactive',
  [CUSTOMER_STATUS.SUSPENDED]: 'Suspended',
  [CUSTOMER_STATUS.BLOCKED]: 'Blocked',
  [CUSTOMER_STATUS.PENDING]: 'Pending',
  [CUSTOMER_STATUS.VERIFIED]: 'Verified',
  [CUSTOMER_STATUS.UNVERIFIED]: 'Unverified',
  [CUSTOMER_STATUS.VIP]: 'VIP',
  [CUSTOMER_STATUS.PREMIUM]: 'Premium',
  [CUSTOMER_STATUS.REGULAR]: 'Regular',
  [CUSTOMER_STATUS.NEW]: 'New',
}

// Customer status descriptions
export const CUSTOMER_STATUS_DESCRIPTIONS = {
  [CUSTOMER_STATUS.ACTIVE]: 'Customer is active and can book appointments',
  [CUSTOMER_STATUS.INACTIVE]: 'Customer has not been active recently',
  [CUSTOMER_STATUS.SUSPENDED]: 'Customer account is temporarily suspended',
  [CUSTOMER_STATUS.BLOCKED]: 'Customer account is blocked from booking',
  [CUSTOMER_STATUS.PENDING]: 'Customer account is pending approval',
  [CUSTOMER_STATUS.VERIFIED]: 'Customer account is verified',
  [CUSTOMER_STATUS.UNVERIFIED]: 'Customer account is not verified',
  [CUSTOMER_STATUS.VIP]: 'VIP customer with special privileges',
  [CUSTOMER_STATUS.PREMIUM]: 'Premium customer with enhanced benefits',
  [CUSTOMER_STATUS.REGULAR]: 'Regular customer status',
  [CUSTOMER_STATUS.NEW]: 'New customer status',
}

// Customer status colors
export const CUSTOMER_STATUS_COLORS = {
  [CUSTOMER_STATUS.ACTIVE]: 'green',
  [CUSTOMER_STATUS.INACTIVE]: 'gray',
  [CUSTOMER_STATUS.SUSPENDED]: 'yellow',
  [CUSTOMER_STATUS.BLOCKED]: 'red',
  [CUSTOMER_STATUS.PENDING]: 'orange',
  [CUSTOMER_STATUS.VERIFIED]: 'blue',
  [CUSTOMER_STATUS.UNVERIFIED]: 'gray',
  [CUSTOMER_STATUS.VIP]: 'gold',
  [CUSTOMER_STATUS.PREMIUM]: 'purple',
  [CUSTOMER_STATUS.REGULAR]: 'blue',
  [CUSTOMER_STATUS.NEW]: 'green',
}

// Customer status icons
export const CUSTOMER_STATUS_ICONS = {
  [CUSTOMER_STATUS.ACTIVE]: 'check-circle',
  [CUSTOMER_STATUS.INACTIVE]: 'clock',
  [CUSTOMER_STATUS.SUSPENDED]: 'pause-circle',
  [CUSTOMER_STATUS.BLOCKED]: 'ban',
  [CUSTOMER_STATUS.PENDING]: 'hourglass-half',
  [CUSTOMER_STATUS.VERIFIED]: 'check-circle',
  [CUSTOMER_STATUS.UNVERIFIED]: 'exclamation-circle',
  [CUSTOMER_STATUS.VIP]: 'crown',
  [CUSTOMER_STATUS.PREMIUM]: 'star',
  [CUSTOMER_STATUS.REGULAR]: 'user',
  [CUSTOMER_STATUS.NEW]: 'user-plus',
}

// Customer status categories
export const CUSTOMER_STATUS_CATEGORIES = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  RESTRICTED: 'restricted',
  PENDING: 'pending',
  PREMIUM: 'premium',
}

// Customer status to category mapping
export const CUSTOMER_STATUS_CATEGORY_MAPPING = {
  [CUSTOMER_STATUS.ACTIVE]: CUSTOMER_STATUS_CATEGORIES.ACTIVE,
  [CUSTOMER_STATUS.VERIFIED]: CUSTOMER_STATUS_CATEGORIES.ACTIVE,
  [CUSTOMER_STATUS.REGULAR]: CUSTOMER_STATUS_CATEGORIES.ACTIVE,
  [CUSTOMER_STATUS.NEW]: CUSTOMER_STATUS_CATEGORIES.ACTIVE,
  [CUSTOMER_STATUS.INACTIVE]: CUSTOMER_STATUS_CATEGORIES.INACTIVE,
  [CUSTOMER_STATUS.UNVERIFIED]: CUSTOMER_STATUS_CATEGORIES.INACTIVE,
  [CUSTOMER_STATUS.SUSPENDED]: CUSTOMER_STATUS_CATEGORIES.RESTRICTED,
  [CUSTOMER_STATUS.BLOCKED]: CUSTOMER_STATUS_CATEGORIES.RESTRICTED,
  [CUSTOMER_STATUS.PENDING]: CUSTOMER_STATUS_CATEGORIES.PENDING,
  [CUSTOMER_STATUS.VIP]: CUSTOMER_STATUS_CATEGORIES.PREMIUM,
  [CUSTOMER_STATUS.PREMIUM]: CUSTOMER_STATUS_CATEGORIES.PREMIUM,
}

// Customer status priority (higher number = higher priority)
export const CUSTOMER_STATUS_PRIORITY = {
  [CUSTOMER_STATUS.VIP]: 5,
  [CUSTOMER_STATUS.PREMIUM]: 4,
  [CUSTOMER_STATUS.ACTIVE]: 3,
  [CUSTOMER_STATUS.VERIFIED]: 3,
  [CUSTOMER_STATUS.REGULAR]: 3,
  [CUSTOMER_STATUS.NEW]: 2,
  [CUSTOMER_STATUS.PENDING]: 2,
  [CUSTOMER_STATUS.INACTIVE]: 1,
  [CUSTOMER_STATUS.UNVERIFIED]: 1,
  [CUSTOMER_STATUS.SUSPENDED]: 0,
  [CUSTOMER_STATUS.BLOCKED]: 0,
}

// Customer status transitions (what statuses can be changed to)
export const CUSTOMER_STATUS_TRANSITIONS = {
  [CUSTOMER_STATUS.ACTIVE]: [CUSTOMER_STATUS.INACTIVE, CUSTOMER_STATUS.SUSPENDED, CUSTOMER_STATUS.BLOCKED, CUSTOMER_STATUS.VIP, CUSTOMER_STATUS.PREMIUM],
  [CUSTOMER_STATUS.INACTIVE]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.SUSPENDED, CUSTOMER_STATUS.BLOCKED],
  [CUSTOMER_STATUS.SUSPENDED]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.BLOCKED],
  [CUSTOMER_STATUS.BLOCKED]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.SUSPENDED],
  [CUSTOMER_STATUS.PENDING]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.BLOCKED],
  [CUSTOMER_STATUS.VERIFIED]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.INACTIVE, CUSTOMER_STATUS.VIP, CUSTOMER_STATUS.PREMIUM],
  [CUSTOMER_STATUS.UNVERIFIED]: [CUSTOMER_STATUS.VERIFIED, CUSTOMER_STATUS.BLOCKED],
  [CUSTOMER_STATUS.VIP]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.PREMIUM, CUSTOMER_STATUS.INACTIVE],
  [CUSTOMER_STATUS.PREMIUM]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.VIP, CUSTOMER_STATUS.INACTIVE],
  [CUSTOMER_STATUS.REGULAR]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.PREMIUM, CUSTOMER_STATUS.VIP, CUSTOMER_STATUS.INACTIVE],
  [CUSTOMER_STATUS.NEW]: [CUSTOMER_STATUS.ACTIVE, CUSTOMER_STATUS.REGULAR, CUSTOMER_STATUS.BLOCKED],
}

// Available customer statuses for selection
export const AVAILABLE_CUSTOMER_STATUSES = Object.values(CUSTOMER_STATUS).map(status => ({
  value: status,
  label: CUSTOMER_STATUS_DISPLAY_NAMES[status],
  description: CUSTOMER_STATUS_DESCRIPTIONS[status],
  color: CUSTOMER_STATUS_COLORS[status],
  icon: CUSTOMER_STATUS_ICONS[status],
  category: CUSTOMER_STATUS_CATEGORY_MAPPING[status],
  priority: CUSTOMER_STATUS_PRIORITY[status],
  transitions: CUSTOMER_STATUS_TRANSITIONS[status],
}))

export default {
  CUSTOMER_STATUS,
  CUSTOMER_STATUS_DISPLAY_NAMES,
  CUSTOMER_STATUS_DESCRIPTIONS,
  CUSTOMER_STATUS_COLORS,
  CUSTOMER_STATUS_ICONS,
  CUSTOMER_STATUS_CATEGORIES,
  CUSTOMER_STATUS_CATEGORY_MAPPING,
  CUSTOMER_STATUS_PRIORITY,
  CUSTOMER_STATUS_TRANSITIONS,
  AVAILABLE_CUSTOMER_STATUSES,
}
