import React, { useState } from 'react'
import { Card, Button, Input, Dropdown, DatePicker, Badge } from '../../common'

const ReportFilters = ({ 
  filters = {},
  onFiltersChange,
  onClearFilters,
  onApplyFilters,
  reportTypes = [],
  categories = [],
  statuses = [],
  generatedBy = [],
  className = ''
}) => {
  const [localFilters, setLocalFilters] = useState(filters)

  const handleFilterChange = (key, value) => {
    const newFilters = {
      ...localFilters,
      [key]: value
    }
    setLocalFilters(newFilters)
  }

  const handleClearFilter = (key) => {
    const newFilters = { ...localFilters }
    delete newFilters[key]
    setLocalFilters(newFilters)
  }

  const handleClearAll = () => {
    setLocalFilters({})
    onClearFilters && onClearFilters()
  }

  const handleApply = () => {
    onFiltersChange && onFiltersChange(localFilters)
    onApplyFilters && onApplyFilters(localFilters)
  }

  const getActiveFiltersCount = () => {
    return Object.keys(localFilters).filter(key => 
      localFilters[key] !== '' && 
      localFilters[key] !== null && 
      localFilters[key] !== undefined &&
      !(Array.isArray(localFilters[key]) && localFilters[key].length === 0)
    ).length
  }

  const formatDateRange = (startDate, endDate) => {
    if (!startDate && !endDate) return ''
    if (startDate && endDate) {
      return `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`
    }
    if (startDate) {
      return `From ${new Date(startDate).toLocaleDateString()}`
    }
    if (endDate) {
      return `Until ${new Date(endDate).toLocaleDateString()}`
    }
    return ''
  }

  const renderActiveFilters = () => {
    const activeFilters = []
    
    if (localFilters.search) {
      activeFilters.push({
        key: 'search',
        label: `Search: "${localFilters.search}"`,
        value: localFilters.search
      })
    }
    
    if (localFilters.type) {
      activeFilters.push({
        key: 'type',
        label: `Type: ${localFilters.type}`,
        value: localFilters.type
      })
    }
    
    if (localFilters.category) {
      activeFilters.push({
        key: 'category',
        label: `Category: ${localFilters.category}`,
        value: localFilters.category
      })
    }
    
    if (localFilters.status) {
      activeFilters.push({
        key: 'status',
        label: `Status: ${localFilters.status}`,
        value: localFilters.status
      })
    }
    
    if (localFilters.generatedBy) {
      activeFilters.push({
        key: 'generatedBy',
        label: `Generated By: ${localFilters.generatedBy}`,
        value: localFilters.generatedBy
      })
    }
    
    if (localFilters.dateRange) {
      const dateRange = formatDateRange(localFilters.dateRange.start, localFilters.dateRange.end)
      if (dateRange) {
        activeFilters.push({
          key: 'dateRange',
          label: `Date: ${dateRange}`,
          value: localFilters.dateRange
        })
      }
    }
    
    if (localFilters.tags && localFilters.tags.length > 0) {
      activeFilters.push({
        key: 'tags',
        label: `Tags: ${localFilters.tags.join(', ')}`,
        value: localFilters.tags
      })
    }

    return activeFilters
  }

  return (
    <Card className={className}>
      <div className="p-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="text-lg font-semibold text-gray-900">Filter Reports</h3>
            <p className="text-sm text-gray-600">
              Narrow down your search to find the reports you need
            </p>
          </div>
          <div className="flex gap-2">
            {getActiveFiltersCount() > 0 && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleClearAll}
              >
                Clear All ({getActiveFiltersCount()})
              </Button>
            )}
            <Button
              variant="primary"
              size="sm"
              onClick={handleApply}
            >
              Apply Filters
            </Button>
          </div>
        </div>

        {/* Active Filters */}
        {getActiveFiltersCount() > 0 && (
          <div className="mb-6 p-4 bg-gray-50 ">
            <h4 className="text-sm font-medium text-gray-700 mb-2">Active Filters</h4>
            <div className="flex flex-wrap gap-2">
              {renderActiveFilters().map((filter) => (
                <Badge
                  key={filter.key}
                  variant="primary"
                  className="flex items-center gap-1"
                >
                  {filter.label}
                  <button
                    onClick={() => handleClearFilter(filter.key)}
                    className="ml-1 hover:bg-primary-200 rounded-full p-0.5"
                  >
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                    </svg>
                  </button>
                </Badge>
              ))}
            </div>
          </div>
        )}

        {/* Filter Controls */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Search */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Search Reports
            </label>
            <Input
              type="text"
              placeholder="Search by name, description..."
              value={localFilters.search || ''}
              onChange={(e) => handleFilterChange('search', e.target.value)}
            />
          </div>

          {/* Report Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Report Type
            </label>
            <Dropdown
              options={[
                { label: 'All Types', value: '' },
                ...reportTypes.map(type => ({
                  label: type.label || type,
                  value: type.value || type
                }))
              ]}
              value={localFilters.type || ''}
              onChange={(value) => handleFilterChange('type', value)}
              placeholder="Select report type"
              optionLabel="label"
              optionValue="value"
              clearable
            />
          </div>

          {/* Category */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Category
            </label>
            <Dropdown
              options={[
                { label: 'All Categories', value: '' },
                ...categories.map(category => ({
                  label: category.label || category,
                  value: category.value || category
                }))
              ]}
              value={localFilters.category || ''}
              onChange={(value) => handleFilterChange('category', value)}
              placeholder="Select category"
              optionLabel="label"
              optionValue="value"
              clearable
            />
          </div>

          {/* Status */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Status
            </label>
            <Dropdown
              options={[
                { label: 'All Statuses', value: '' },
                ...statuses.map(status => ({
                  label: status.label || status,
                  value: status.value || status
                }))
              ]}
              value={localFilters.status || ''}
              onChange={(value) => handleFilterChange('status', value)}
              placeholder="Select status"
              optionLabel="label"
              optionValue="value"
              clearable
            />
          </div>

          {/* Generated By */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Generated By
            </label>
            <Dropdown
              options={[
                { label: 'All Users', value: '' },
                ...generatedBy.map(user => ({
                  label: user.label || user,
                  value: user.value || user
                }))
              ]}
              value={localFilters.generatedBy || ''}
              onChange={(value) => handleFilterChange('generatedBy', value)}
              placeholder="Select user"
              optionLabel="label"
              optionValue="value"
              clearable
            />
          </div>

          {/* Date Range */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Date Range
            </label>
            <div className="space-y-2">
              <DatePicker
                selectedDate={localFilters.dateRange?.start}
                onDateChange={(date) => handleFilterChange('dateRange', {
                  ...localFilters.dateRange,
                  start: date
                })}
                placeholder="Start date"
                className="w-full"
              />
              <DatePicker
                selectedDate={localFilters.dateRange?.end}
                onDateChange={(date) => handleFilterChange('dateRange', {
                  ...localFilters.dateRange,
                  end: date
                })}
                placeholder="End date"
                className="w-full"
              />
            </div>
          </div>
        </div>

        {/* Advanced Filters */}
        <div className="mt-6 pt-6 border-t border-gray-200">
          <h4 className="text-sm font-medium text-gray-700 mb-4">Advanced Filters</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* File Size Range */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                File Size Range
              </label>
              <div className="flex gap-2">
                <Input
                  type="number"
                  placeholder="Min (KB)"
                  value={localFilters.fileSize?.min || ''}
                  onChange={(e) => handleFilterChange('fileSize', {
                    ...localFilters.fileSize,
                    min: e.target.value ? parseInt(e.target.value) : null
                  })}
                />
                <Input
                  type="number"
                  placeholder="Max (KB)"
                  value={localFilters.fileSize?.max || ''}
                  onChange={(e) => handleFilterChange('fileSize', {
                    ...localFilters.fileSize,
                    max: e.target.value ? parseInt(e.target.value) : null
                  })}
                />
              </div>
            </div>

            {/* Record Count Range */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Record Count Range
              </label>
              <div className="flex gap-2">
                <Input
                  type="number"
                  placeholder="Min records"
                  value={localFilters.recordCount?.min || ''}
                  onChange={(e) => handleFilterChange('recordCount', {
                    ...localFilters.recordCount,
                    min: e.target.value ? parseInt(e.target.value) : null
                  })}
                />
                <Input
                  type="number"
                  placeholder="Max records"
                  value={localFilters.recordCount?.max || ''}
                  onChange={(e) => handleFilterChange('recordCount', {
                    ...localFilters.recordCount,
                    max: e.target.value ? parseInt(e.target.value) : null
                  })}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Quick Filters */}
        <div className="mt-6 pt-6 border-t border-gray-200">
          <h4 className="text-sm font-medium text-gray-700 mb-4">Quick Filters</h4>
          <div className="flex flex-wrap gap-2">
            <Button
              variant={localFilters.isPublic ? 'primary' : 'outline'}
              size="sm"
              onClick={() => handleFilterChange('isPublic', !localFilters.isPublic)}
            >
              Public Reports
            </Button>
            <Button
              variant={localFilters.hasSchedule ? 'primary' : 'outline'}
              size="sm"
              onClick={() => handleFilterChange('hasSchedule', !localFilters.hasSchedule)}
            >
              Scheduled Reports
            </Button>
            <Button
              variant={localFilters.recentOnly ? 'primary' : 'outline'}
              size="sm"
              onClick={() => handleFilterChange('recentOnly', !localFilters.recentOnly)}
            >
              Recent (Last 7 days)
            </Button>
            <Button
              variant={localFilters.largeFiles ? 'primary' : 'outline'}
              size="sm"
              onClick={() => handleFilterChange('largeFiles', !localFilters.largeFiles)}
            >
                Large Files (&gt;1MB)
            </Button>
          </div>
        </div>
      </div>
    </Card>
  )
}

export default ReportFilters
